blog_post:
    resource: "@BlogBundle/Resources/config/routing/post.yml"
    prefix:   /post

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_category:
    resource: "@BlogBundle/Resources/config/routing/category.yml"
    prefix:   /category


