catalog_index:
    path:     /
    defaults: { _controller: "BlogBundle:Catalog:index" }
    methods:  GET

catalog_show:
    path:     /{id}/show
    defaults: { _controller: "BlogBundle:Catalog:show" }
    methods:  GET

catalog_new:
    path:     /new
    defaults: { _controller: "BlogBundle:Catalog:new" }
    methods:  [GET, POST]

catalog_edit:
    path:     /{id}/edit
    defaults: { _controller: "BlogBundle:Catalog:edit" }
    methods:  [GET, POST]

catalog_delete:
    path:     /{id}/delete
    defaults: { _controller: "BlogBundle:Catalog:delete" }
    methods:  DELETE
